### PR TITLE
fix: improve backend testsuite

### PR DESCRIPTION
**Pull request by Traxmaxx**
## Problem

The testsuite in CI/CD and localy currently reports
```logtalk
Run make test
go test -v 
?   	github.com/tailwarden/komiser	[no test files]
```

## Solution

Tests are executed like `go test -v $(go list ./... | grep -v /dashboard/)` and this is suppossed to work fine, however for unknown reasons it does not when executed through the `Makefile`. Updating the command to `go test ./... | grep -v /dashboard/` and pipe the ignore filter instead works more reliably

## Changes Made

- Update `Makefile` to execute all found tests except inside `/dashboard` folder
- Update GCP pricing map (**[SEE NOTES ](#notes)**)
- Update `CONTRIBUTING.md`
- Update tests `machine_test.go` and refactor how to test because previously we were mapping against a fixed price. I presume (actually it's hope) that the schema changes less often than the prices. I made the tests more dry and only check if the price returned is above a certain number. The number is currently set to `0`.
- Update Feedback Widget to use new Toast component

## How to Test

- Localy: checkout this branch and run `make test` or `go test ./... | grep -v /dashboard/`
- CI/CD: check the run results of the latest commit in this PR. Is should look similar to the attached screenshot!

## Screenshots

Screenshot 2023-10-20 at 13 47 34
Screenshot 2023-10-20 at 13 25 03

## Notes

There are test fixes in here as well.
For example `/utils/gcpcomputepricing` was broken. It seems like Google updated their pricing structure? 
Comparing our current `VmsOnDemandMemoryPerGb` type with the content returned from [gcp-compute.json](https://www.gstatic.com/cloud-site-ux/pricing/data/gcp-compute.json) it seems they now nest `Vmimagee2RAME2` instance type under `E2` (sdee screenshot attached). 
I updated the types being used in the utils test and the test now passes without error.

Before the tests where returning

```logtalk
--- FAIL: TestGet (0.32s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0
--- FAIL: TestGetE2standard32OnDemand (0.08s)
    machine_test.go:62: core price not found for "us-west1" region
```

Also check comment thread please.

## Checklist

- [x] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [x] Changes have been thoroughly tested
- [x] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [x] Any dependencies have been added to the project, if necessary

## Reviewers

@[username of the reviewer]

### CODE REVIEW

**Comment by shavidze** [comment]
Can I help you?

**Comment by Traxmaxx** [comment]
@shavidze yes please. Do you think my observations are right? Or is there something else wrong with the GCP pricing tests?
I was unable to find any sort of changelog for https://www.gstatic.com/cloud-site-ux/pricing/data/gcp-compute.json

**Comment by Traxmaxx** [comment]
Just for references: this PR introduced the above mentioned mapping and it seemed to have worked fine back then #652

**Comment by shavidze** [comment]
@Traxmaxx I will take a look.

**Comment by Traxmaxx** [comment]
@shavidze me and @mlabouardy came to the conclution that the pricemapping indeed changed. There are more types to update and we should rethink maybe if we really want to test all prices so detailed or if we should just check for a value greater than `0`

**Comment by Traxmaxx** [comment]
So that should be all for `gcpcomputepricing` 🤞

**Comment by AvineshTripathi** [comment]
Hey @Traxmaxx there are some frontend changes too included in the PR please confirm if you want to include in this PR and let me know when I can test this... Excited!

**Comment by Traxmaxx** [comment]
@AvineshTripathi its ready. I was just fixing test and lint errors in the frontend so the PR is green!

**Review by AvineshTripathi — COMMENTED** [review]
@Traxmaxx  great work man! I didnt see anything more in that to review. Although I wanted to ask if we should move pricing logic of gcp inside something like `/utils/pricing/gcp` and structurize file structure in that more for maintaining

**Comment by Traxmaxx** [comment]
So what is the status of this PR? Anything else I should change?
@mlabouardy @AvineshTripathi @ShubhamPalriwala @jakepage91 ?

**Review by mlabouardy — APPROVED** [review]
All good :)

**Pull request merged**
