### PR TITLE
Migration Nextjs 13 to 14

### PR DESCRIPTION
**Pull request by shivam-sharma7**
Migration Nextjs 13 to 14
 

## Changes Made

- [List the changes you made in this pull request, including any new features or bug fixes.]

## How to Test

[Provide instructions on how to test the changes you made, including any relevant details like configuration steps or data to be used for testing.]

## Screenshots

[Include screenshots, if relevant, to help reviewers understand the changes you made.]

## Notes

[Any additional notes or information that you would like to share with the reviewers.]

## Checklist

- [ ] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [ ] Changes have been thoroughly tested
- [ ] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [ ] Any dependencies have been added to the project, if necessary

## Reviewers

@[username of the reviewer]

### CODE REVIEW

**Comment by AvineshTripathi** [comment]
Hey @ShubhamPalriwala I think you had some comments regarding nextjs if I m not wrong

**Comment by Traxmaxx** [comment]
Hey, for this to be merged the build steps need to succeed. Is there any help needed?

**Comment by shivam-sharma7** [comment]
> Hey, for this to be merged the build steps need to succeed. Is there any help needed?

@Traxmaxx yes ci not passing but you try to build my branch in locally if everything would be good. then it is not mendetory to ci should be pass. sometime we need to explore and address the issue. honestly, I have't find something yet to fix it. if you have any solution then it would be apreciated:)

**Comment by Traxmaxx** [comment]
@shivam-sharma7 sorry but I disagree. All build should be green before merging and the error is quite clear: 
>   The "next export" command has been removed in favor of "output: export" in next.config.js. Learn more: https://nextjs.org/docs/advanced-features/static-html-export

Looking at how the export is done atm:
Screenshot 2023-11-21 at 14 26 48

The solution should be quite clear. If this is not being addressed the PR will be closed. It's not being deprecated here but being removed! So export is broken!

**Comment by ShubhamPalriwala** [comment]
> Hey @ShubhamPalriwala I think you had some comments regarding nextjs if I m not wrong

Hellooo, not directly to this PR! Migration to app directory will be a task that needs to be in parallel and does not depend/ask Next to be 14 as such! So it will be an independent effort

**Comment by shivam-sharma7** [comment]
> > Hey @ShubhamPalriwala I think you had some comments regarding nextjs if I m not wrong
> 
> Hellooo, not directly to this PR! Migration to app directory will be a task that needs to be in parallel and does not depend/ask Next to be 14 as such! So it will be an independent effort

We can have another PR!

**Comment by Traxmaxx** [comment]
@shivam-sharma7 there still needs to be `"output: export"` in next.config.js.
https://nextjs.org/docs/pages/building-your-application/deploying/static-exports

It should be good to merge then. Thanks for the fixes! 🙏

**Comment by shivam-sharma7** [comment]
> @shivam-sharma7 there still needs to be `"output: export"` in next.config.js. https://nextjs.org/docs/pages/building-your-application/deploying/static-exports
> 
> It should be good to merge then. Thanks for the fixes! 

@Traxmaxx give a look!

**Review by Traxmaxx — APPROVED** [review]

**Comment by Traxmaxx** [comment]
@shivam-sharma7 LGTM. Thanks for the PR and fixing the export! 🙏 💚

**Comment by shivam-sharma7** [comment]
Thanks!

**Pull request merged**
