### PR TITLE
Create instances.go

### PR DESCRIPTION
**Pull request by akshayamadhuri**
issue no: #251 

[Include screenshots, if relevant, to help reviewers understand the changes you made.]

## Notes

[Any additional notes or information that you would like to share with the reviewers.]

## Checklist

- [x] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [ ] Changes have been thoroughly tested
- [ ] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [ ] Any dependencies have been added to the project, if necessary

## Reviewers

@[username of the reviewer]

### CODE REVIEW

**Comment by Kolawole99** [comment]
@akshayamadhuri can you kindly update the PR description and add a link to the issue this PR resolves for tracking?

**Comment by AvineshTripathi** [comment]
Do you need any help with this PR @akshayamadhuri

**Comment by akshayamadhuri** [comment]
@AvineshTripathi  can you please reveiw it and suggest if need any changes

**Comment by AvineshTripathi** [comment]
@akshayamadhuri the imports are incorrect please change those and also please test it and push and I'll be happy to review it thanks

**Review by Kolawole99 — CHANGES_REQUESTED** [review]
@akshayamadhuri there seems to be missing variable declaration and imports that are being flagged by the go compiler. 

Basically, can you take a look at the code in the file and try to run the backend; while fixing any issues caught by the compiler?

Here is some documentation that might help you get up to speed on running the backend and checking if Redshift data shows up in the UI as populated from the backend.

How to Contribute: https://www.youtube.com/watch?v=Vn5uc2elcVg
https://docs.komiser.io/community-support/contributing

**Comment by mlabouardy** [comment]
Due to inactivity, I'm closing this PR for now, feel free to open it again @akshayamadhuri once the above changes are made :)

**Pull request closed without merging**
