### PR TITLE
Use latest tailwind css v3.3.3

### PR DESCRIPTION
**Pull request by shivam-sharma7**
use latest tailwind css v3.3.3

[Provide a brief description of the problem that you are trying to solve with this pull request.]

## Solution

[Provide a detailed explanation of the solution you are proposing, including any relevant code snippets or screenshots.]

## Changes Made

- [List the changes you made in this pull request, including any new features or bug fixes.]

## How to Test

[Provide instructions on how to test the changes you made, including any relevant details like configuration steps or data to be used for testing.]

## Screenshots

[Include screenshots, if relevant, to help reviewers understand the changes you made.]

## Notes

[Any additional notes or information that you would like to share with the reviewers.]

## Checklist

- [x] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [ ] Changes have been thoroughly tested
- [ ] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [x] Any dependencies have been added to the project, if necessary

### CODE REVIEW

**Comment by AvineshTripathi** [comment]
I am not really sure if updating versions manually is better I think updates should be done when required or those that comes with some changes and while doing the changes version updates directly. Thoughts? cc @Traxmaxx

**Comment by shivam-sharma7** [comment]
Updating version mean keep project up-to-date with latest tech stack, why? bacause If you would't update  the version of dep.. then you don't understand what is breaking in project, if you see in CI then you got relize, plus i would say don't bear the pain of migration otherwise that will take much time:)

**Comment by Kolawole99** [comment]
I agree with @AvineshTripathi on manually updating packages, we should either find a way to automate this or schedule a time for updating packages.

**Comment by Traxmaxx** [comment]
Correct me if I'm wrong but dependabot is taking care of package upgrades in this repo right?

While I agree that packages should be upgraded rather sooner than later, just upgrading them for the purpose of upgrading is defeting the purpose I feel. For example while tailwindcss got upgraded in this PR, why is `prettier-plugin-tailwindcss` still on `^0.2.2` while the latest release is `0.5.4`? Also the PR desciption is not filled out properly and I don't understand why this upgrade is being done.

**Pull request closed without merging**
