### PR TITLE
Update policy.json

### PR DESCRIPTION
**Pull request by professorabhay**
fix-issue(#852)

### CODE REVIEW

**Comment by professorabhay** [comment]
Hey @ShubhamPalriwala, You can test the policy now.
Let me know the result after you test it out. 
`https://github.com/professorabhay/komiser/blob/fix-issue(%23852)-IAM-POLICY/policy.json`

**Review by ShubhamPalriwala — CHANGES_REQUESTED** [review]
Hey @professorabhay, I took a quick glance and do not remember seeing a ListBuckets action in AWS? Can you confirm that please? I think it was something like ListAllMyBuckets?

And have you verified that this covers all the resources we fetch?

**Comment by professorabhay** [comment]
Hey @ShubhamPalriwala, I take a look to the original `\policy.json` file and didn't find any `ListAllMyBuckets` action.
But here it will work fine.

No, I didn't. This commit remove all the errors and wildcard. I didn't add or remove any resource. 
As mentioned in issue to add all the lately added resources. Please provide me guidance, How I can find all the resources Komiser fetch?
Let me know and I will come with new update asap!!

**Comment by professorabhay** [comment]
image
On the official documentation `https://docs.komiser.io/docs/cloud-providers/aws` I found that. 
These are the resources which is supported. 
Are you talking about them ??

**Comment by ShubhamPalriwala** [comment]
Hey @professorabhay, yes, the docs should mostly cover all the resources we support, additionally just take a look here https://github.com/tailwarden/komiser/tree/develop/providers/aws and see if there is anything missing in the docs that is present here!

**Review by mlabouardy — CHANGES_REQUESTED** [review]
Thanks for the PR @professorabhay but there are a couple of permissions missing such as:
`cloudfront:ListTagsForResource`
As mentioned by @ShubhamPalriwala I recommend you go through the supported services here https://github.com/tailwarden/komiser/tree/develop/providers/aws and add the missing permissions to the JSON file.

**Comment by professorabhay** [comment]
Hey @mlabouardy, Thanks for review.
I am still working it. I just look deeply into it and creating policy from scratch. I'll commit changes again.

**Comment by ShubhamPalriwala** [comment]
@professorabhay, let me know if you need any help here

**Comment by professorabhay** [comment]
hey @ShubhamPalriwala, I make changes.
please test it and let me know if it give error.

**Comment by ShubhamPalriwala** [comment]
Hey @professorabhay, I just tried to validate it and faced the following errors:
Screenshot_2023-06-24-14-01-51_4920x1920

To reproduce it,
- Login to the AWS Console
- Look for IAM
- Look for Creating Policies
- Look for a **JSON** button
- Now copy paste your policy and you should be able to see the 3 errors.

PS: The above does not require any AWS credits so should be doable as well easily! Let me know if you need any help with it

**Comment by mlabouardy** [comment]
> Hey @professorabhay, I just tried to validate it and faced the following errors: Screenshot_2023-06-24-14-01-51_4920x1920
> 
> To reproduce it,
> 
> * Login to the AWS Console
> * Look for IAM
> * Look for Creating Policies
> * Look for a **JSON** button
> * Now copy paste your policy and you should be able to see the 3 errors.
> 
> PS: The above does not require any AWS credits so should be doable as well easily! Let me know if you need any help with it

Any update on this @professorabhay ?

**Comment by professorabhay** [comment]
I will make changes by the end of this week

**Comment by ShubhamPalriwala** [comment]
Hey @professorabhay can we plan this for the next release ie sometime this week?

**Comment by professorabhay** [comment]
Hai @ShubhamPalriwala, Kindly take a look

**Review by ShubhamPalriwala — CHANGES_REQUESTED** [review]
Hey @professorabhay, apologies for the delay in review! I can still see some errors:
image

Was it working for you in your AWS IAM account?

**Comment by professorabhay** [comment]
Hey @AvineshTripathi, I'll be great that you can help me. I gave it a try while learning but it's way more difficult to solve. 
Looking forward to resolve it asap under your guidance!!

**Comment by AvineshTripathi** [comment]
Here is the one I generated without error
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "1",
      "Effect": "Allow",
      "Action": [
        "ec2:Describe*",
        "elasticloadbalancing:Describe*",
        "autoscaling:Describe*",
        "s3:ListBucket",
        "s3:GetObject",
        "ecs:List*",
        "ce:GetCostAndUsage",
        "ce:GetCostForecast",
        "dynamodb:Describe*"
      ],
      "Resource": "*"
    },
    {
      "Sid": "2",
      "Effect": "Allow",
      "Action": [
        "lambda:List*",
        "dynamodb:List*",
        "cloudfront:List*",
        "iam:List*",
        "ecs:Describe*",
        "glacier:List*",
        "sqs:List*",
        "route53:List*",
        "sns:List*",
        "s3:Get*"
      ],
      "Resource": "*"
    },
    {
      "Sid": "3",
      "Effect": "Allow",
      "Action": [
        "acm:List*",
        "mq:List*",
        "cloudwatch:Get*",
        "cloudtrail:LookupEvents",
        "datapipeline:List*",
        "eks:List*",
        "elasticache:Describe*",
        "es:List*",
        "logs:Describe*",
        "rds:Describe*",
        "cloudwatch:Describe*",
        "apigateway:GET",
        "cloudwatch:List*",
        "dynamodb:List*",
        "ec2:Describe*",
        "ecr:Describe*",
        "ecs:Describe*",
        "eks:Describe*",
        "elasticache:List*",
        "elasticloadbalancing:Describe*",
        "iam:List*",
        "kinesis:List*",
        "kms:List*",
        "lambda:List*",
        "rds:Describe*",
        "s3:List*",
        "servicecatalog:List*",
        "sns:List*",
        "sqs:List*"
      ],
      "Resource": "*"
    },
    {
      "Sid": "4",
      "Effect": "Allow",
      "Action": [
        "glue:Get*",
        "organizations:Describe*",
        "iam:Get*",
        "kinesis:List*",
        "kms:List*",
        "kms:Describe*",
        "redshift:Describe*",
        "tag:Get*",
        "route53:List*",
        "support:Describe*",
        "swf:List*",
        "config:BatchGetResourceConfig"
      ],
      "Resource": "*"
    },
    {
      "Sid": "5",
      "Effect": "Allow",
      "Action": [
        "sns:List*",
        "lambda:List*",
        "kms:List*",
        "pricing:GetProducts",
        "ecr:Describe*",
        "rds:Describe*",
        "elasticache:List*",
        "eks:Describe*",
        "elasticloadbalancing:DescribeTags"
      ],
      "Resource": "*"
    }
  ]
}

```

cc @mlabouardy  @ShubhamPalriwala for review

**Comment by mlabouardy** [comment]
> {
>   "Version": "2012-10-17",
>   "Statement": [
>     {
>       "Sid": "1",
>       "Effect": "Allow",
>       "Action": [
>         "ec2:Describe*",
>         "elasticloadbalancing:Describe*",
>         "autoscaling:Describe*",
>         "s3:ListBucket",
>         "s3:GetObject",
>         "ecs:List*",
>         "ce:GetCostAndUsage",
>         "ce:GetCostForecast",
>         "dynamodb:Describe*"
>       ],
>       "Resource": "*"
>     },
>     {
>       "Sid": "2",
>       "Effect": "Allow",
>       "Action": [
>         "lambda:List*",
>         "dynamodb:List*",
>         "cloudfront:List*",
>         "iam:List*",
>         "ecs:Describe*",
>         "glacier:List*",
>         "sqs:List*",
>         "route53:List*",
>         "sns:List*",
>         "s3:Get*"
>       ],
>       "Resource": "*"
>     },
>     {
>       "Sid": "3",
>       "Effect": "Allow",
>       "Action": [
>         "acm:List*",
>         "mq:List*",
>         "cloudwatch:Get*",
>         "cloudtrail:LookupEvents",
>         "datapipeline:List*",
>         "eks:List*",
>         "elasticache:Describe*",
>         "es:List*",
>         "logs:Describe*",
>         "rds:Describe*",
>         "cloudwatch:Describe*",
>         "apigateway:GET",
>         "cloudwatch:List*",
>         "dynamodb:List*",
>         "ec2:Describe*",
>         "ecr:Describe*",
>         "ecs:Describe*",
>         "eks:Describe*",
>         "elasticache:List*",
>         "elasticloadbalancing:Describe*",
>         "iam:List*",
>         "kinesis:List*",
>         "kms:List*",
>         "lambda:List*",
>         "rds:Describe*",
>         "s3:List*",
>         "servicecatalog:List*",
>         "sns:List*",
>         "sqs:List*"
>       ],
>       "Resource": "*"
>     },
>     {
>       "Sid": "4",
>       "Effect": "Allow",
>       "Action": [
>         "glue:Get*",
>         "organizations:Describe*",
>         "iam:Get*",
>         "kinesis:List*",
>         "kms:List*",
>         "kms:Describe*",
>         "redshift:Describe*",
>         "tag:Get*",
>         "route53:List*",
>         "support:Describe*",
>         "swf:List*",
>         "config:BatchGetResourceConfig"
>       ],
>       "Resource": "*"
>     },
>     {
>       "Sid": "5",
>       "Effect": "Allow",
>       "Action": [
>         "sns:List*",
>         "lambda:List*",
>         "kms:List*",
>         "pricing:GetProducts",
>         "ecr:Describe*",
>         "rds:Describe*",
>         "elasticache:List*",
>         "eks:Describe*",
>         "elasticloadbalancing:DescribeTags"
>       ],
>       "Resource": "*"
>     }
>   ]
> }

thanks Avinesh, I noticed that some permissions are duplicated for example:
"s3:ListBucket",
"s3:GetObject"
with:
"s3:Get*"
"s3:List*"
 
could you merge them? :)

**Comment by AvineshTripathi** [comment]
Any reason why we are using multiplee statement inplace of single, is there a best practice we should follow?

**Comment by AvineshTripathi** [comment]
@professorabhay if it is Okay for you can I close thiis PR and create a new one to get changes fast and also I can add you as co-author if you want

**Comment by professorabhay** [comment]
Sure @AvineshTripathi !

**Pull request closed without merging**
