### PR TITLE
Update Komiser AWS IAM Policy

### PR DESCRIPTION
**Pull request by professorabhay**
Update Komiser AWS IAM Policy #852

## Problem

Solve fetch permissions errors problem

## Solution

That modified version of code will able to do this.

## Changes Made

policy.json

## How to Test

Run the code

## Screenshots

Nil.

## Notes

I was not able to test that Policy on AWS because my account is locked

## Reviewers

@jakepage91  @ShubhamPalriwala

### CODE REVIEW

**Comment by jakepage91** [comment]
LGTM

**Comment by professorabhay** [comment]
Great @jakepage91

**Review by ShubhamPalriwala — CHANGES_REQUESTED** [review]
Hey @professorabhay, great work on the PR! Just a few suggestions from my end:
- Can you create a separate file for the mysql instances? something like `linode/sql/sql.go`?
- Can you also try adding the cost based on the metadata from here: https://www.linode.com/products/mysql/
- And for the resource policy, did you test it? Does this remove all the permission errors?
- And also do verify if we have added support for additional resources that might be missing in the policy.

I'm really looking forward to your changes! Do ping me once you've implemented, would be happy to review again. Do ping me for any help/queries 🚀

**Comment by professorabhay** [comment]
Hey @ShubhamPalriwala,

1.  I can create the separate file as you told. 
2.  I'm confused b/w you wanna add costs by region as shown on `https://www.linode.com/products/mysql/` as a cluster fees     
     or you want to retrieve the cost from the metadata.
3.  I was tried to check it out on AWS but at last they block my card and account also. So, I don't check but I'm pretty sure 
     that it will work fine.

Please help me with the 2nd point and It would we great if you can provide me some credits of AWS or test by self.

**Comment by professorabhay** [comment]
@ShubhamPalriwala 
I am also planned to separate the PR's for the both files `MySQL Instance` and `IAM Policy` .
So that it would be easy to modify and review them.

**Pull request closed without merging**
