### PR TITLE
fix: overlay opacity

### LINKED ISSUE #1279: Modal underlying overlay has full opacity
**Describe the bug**
When a modal or side panel opens, the darker overlay has full opacity, which goes against previous implementations and designs.

**To Reproduce**
1. I clicked on the 'Leave feedback' button.
2. The modal opened, with a backdrop that obscures the rest of the page.

**Expected behavior**
There should be an overlay on top of the underlying layout, but it should have lower opacity as it did in previous releases and as it's documented on the designs.

**Screenshots**
image

**Desktop**
OS: iOS
Browser: Chrome
Version: 119

**Additional context**
The link where the bug happened: /inventory

Once assigned, please reach out to me so I can invite you to the Figma file and tag you on the design to use as a reference.

### PR DESCRIPTION
**Pull request by ManishBisht777**
##Fixes #1279  

## Changes Made

- changed overlay opacity to match Figma

## How to Test

- Click on leave feedback the overlay is slightly transparent
- Click on save as view while creating custom views on the `/inventory`

## Screenshots
image
image

## Checklist

- [x] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [x] Changes have been thoroughly tested
- [ ] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [ ] Any dependencies have been added to the project, if necessary

### CODE REVIEW

**Review by jakepage91 — COMMENTED** [review]
Hey there @ManishBisht777 thanks a million, the overlay issue looks to be addressed thanks a million for that. One thing that I have noticed is that on the Cloud Accounts Page a bug has reappeared (not sure if it's due to the changes done here) There is a solid div over the cloud accounts which shouldn't be there (not there in the current stable version of Komiser v3.1.6) so just wondering if you could check that. Here is the link to the original div bug. https://github.com/tailwarden/komiser/issues/1257
Screenshot 2023-12-15 at 11 35 46

Thanks again.

**Comment by ManishBisht777** [comment]
sure @jakepage91 i'll look into the issue and fix it in this pr itself

**Comment by AvineshTripathi** [comment]
LGTM however would suggest someone with frontend experience review why the remove div from the cloud_account even existed

**Comment by Azanul** [comment]
@AllieMendes Could you please verify that this is the intended change.

**Comment by jakepage91** [comment]
@Azanul I have checked with Allie, and this was the intended change. I still see the div for some reason when building the binary from Manish's fork. Avinesh has confirmed on his side. @Azanul if you test and see that the div is actually gone, then we can move ahead here. It's probably I'm doing something wrong (even though not sure what.)

**Review by jakepage91 — APPROVED** [review]
Good to go

**Review by mlabouardy — APPROVED** [review]

**Comment by jakepage91** [comment]
Thanks a million @ManishBisht777 !

**Pull request merged**
