### PR TITLE
fix: resource tags length

### PR DESCRIPTION
**Pull request by knav33n**
## Problem

[844](https://github.com/tailwarden/komiser/issues/844)

## Changes Made

- Added relevant tailwind classes to InventoryTableTags
- Bump tailwindcss to v3.3.2

## Checklist

- [x] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [x] Changes have been thoroughly tested
- [ ] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [x] Any dependencies have been added to the project, if necessary

## Reviewers

@mlabouardy

### CODE REVIEW

**Review by mlabouardy — APPROVED** [review]
All good, thanks @knav33n

**Comment by mlabouardy** [comment]
@knav33n before I merge, do you mind fixing the conflicts on package-lock.json?

**Comment by knav33n** [comment]
@mlabouardy I've fixed the merge conflicts with package-lock.json.

**Review by ShubhamPalriwala — APPROVED** [review]
Thanks a lot for the fix! Looks amazing and to the point! Just triggered the CI, once it passes we should be gtg!

**Pull request merged**
