### PR TITLE
feat:  calculate civo db costs

### LINKED ISSUE #603: Estimate cost of CIVO Databases
**Describe the solution you'd like**
Estimate cost of CIVO Databases

**Additional context**
To get an idea of how to estimate cost, take the [CIVO objectstore](https://github.com/tailwarden/komiser/blob/master/providers/civo/storage/objectstores.go) resource as an example

### PR DESCRIPTION
**Pull request by ShubhamPalriwala**
## Problem
Closes #603 

## Solution
```go
monthlyCost := float64((resourceInGB / 20) * (20 + (resource.Nodes-1)*15))
```
## Changes Made

- providers/civo/storage/databases.go

## How to Test
Try any configuration mentioned in the table in Civo pricing and it should validate. https://www.civo.com/pricing

## Screenshots
Tested through ChatGPT :))) 
Screenshot_2023-04-04-17-16-20_3000x1920

## Notes
Have made the assumption that:
- the resource.Size will always be added in GigaBytes
- the resource.Nodes are the total nodes and not just the additional nodes (meaning there will always be 1 node)

## Checklist

- [x] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [x] Changes have been thoroughly tested
- [ ] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [x] Any dependencies have been added to the project, if necessary

## Reviewers

@jakepage91 
@mlabouardy 

PS: do not know who to tag here :/ let me know who to for the future

### CODE REVIEW

**Comment by eneskaya** [comment]
Hey @ShubhamPalriwala, I didn't quite get your formula tbh. From our understanding the pricing goes like this:

```
pricing = (memory size/2)*10 + (cpu cores/2)*20 + (storage size/20)*10 + (number of nodes)*15
```

Could you explain your approach?

**Comment by ShubhamPalriwala** [comment]
So how I understood it,
- The cost for a 20GB of an instance with a single node is 20$.
- Each additional node adds an extra 15$


Now the storage the user chooses (whatever multiple of 20), multiply that to the base value(20) and to the additional nodes(15 per extra)

The amount of RAM/memory stays constant ie 1/10th of the storage space. The same happens for the CPUs as well.

Hence we only need either of Storage and number of nodes to compute the cost

**Comment by ShubhamPalriwala** [comment]
For reference:
Screenshot_2023-04-04-20-53-05_3000x1920

**Comment by mlabouardy** [comment]
> So how I understood it,
> 
> * The cost for a 20GB of an instance with a single node is 20$.
> * Each additional node adds an extra 15$
> 
> Now the storage the user chooses (whatever multiple of 20), multiply that to the base value(20) and to the additional nodes(15 per extra)
> 
> The amount of RAM/memory stays constant ie 1/10th of the storage space. The same happens for the CPUs as well.
> 
> Hence we only need either of Storage and number of nodes to compute the cost

if we took this setup as an example: 40Gb NVME with 2 nodes, by following your formula, the pricing should be 70$/month while in the table its 100$/month

**Comment by ShubhamPalriwala** [comment]
Yeah, it should be 70 only in my opinion as out of 2 nodes (1 is **additonal**).

The 100 in the table is for 2 additional nodes making it 3 nodes in total.

Let me know if I got wrong at understanding somewhere.

**Review by mlabouardy — APPROVED** [review]

**Pull request merged**
