### PR TITLE
chore: Update policy.json

### PR DESCRIPTION
**Pull request by kkumtree**
## Problem

I'm new for komiser, so I follow up practical guide on [Tailwarden's Blog](https://www.tailwarden.com/blog/deploy-komiser-to-aws-with-terraform).

When I create a IAM policy, I met the following error.

```text
# AWS Web Console said-
Ln 11, Col 4 | Invalid Action: The action cloudfront:Functions does not exist.
```

## Solution

- Edit IAM policy

## Changes Made

```json
# From 
"cloudfront:Functions",

# To
"cloudfront:ListDistributionsByLambdaFunction",
"cloudfront:ListFunctions",
"cloudfront:DescribeFunction",
"cloudfront:GetFunction",
```

## Screenshots

Invalid error occured
CloudFront statements in scope of ReadOnly

## Checklist

- [x] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [x] Changes have been thoroughly tested
- [ ] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [ ] Any dependencies have been added to the project, if necessary

## Reviewers

@[username of the reviewer]

### CODE REVIEW

**Comment by Azanul** [comment]
@kkumtree target develop branch not master

**Comment by kkumtree** [comment]
> @kkumtree target develop branch not master

Sorry for inconvenience. I change target `develop` branch now. Thanks.

**Comment by Azanul** [comment]
@kkumtree I don't think you'll get the error now. Please do confirm, if so then I don't think the PR is required

**Comment by kkumtree** [comment]
I think, I have to close this pull request, cause of misunderstanding contribution rule. 😅  
And I'll use new master branch on my local environment... Really Sorry;

**Pull request closed without merging**
