### PR TITLE
chore(eslint, tsconfig): path resolution and additional eslint config and fix consitent type imports

### PR DESCRIPTION
**Pull request by dammy001**
## Problem

[Provide a brief description of the problem that you are trying to solve with this pull request.]

## Solution

[Provide a detailed explanation of the solution you are proposing, including any relevant code snippets or screenshots.]

## Changes Made

- Fix consistent type imports
- Added auto-import plugin (https://github.com/antfu/unplugin-auto-import)
- Added path resolutions.
- Formatting

## How to Test

[Provide instructions on how to test the changes you made, including any relevant details like configuration steps or data to be used for testing.]

## Screenshots

[Include screenshots, if relevant, to help reviewers understand the changes you made.]

## Notes

[Any additional notes or information that you would like to share with the reviewers.]

## Checklist

- [x] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [x] Changes have been thoroughly tested
- [ ] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [ ] Any dependencies have been added to the project, if necessary

## Reviewers

@[username of the reviewer]

### CODE REVIEW

**Comment by dammy001** [comment]
@victorgaard @eneskaya ready for review now

**Comment by dammy001** [comment]
@mlabouardy any update on this PR?

**Comment by dammy001** [comment]
> > @mlabouardy any update on this PR?
> 
> Hi @dammy001 Thanks for the PR. Can you update the PR please to latest develop branch? As for the delay, since it's a big PR, we need a bit more time going through and discussing the changes. We'll get back to it ASAP

Okay. Thanks

**Comment by dammy001** [comment]
@eneskaya conflicts resolved

**Comment by eneskaya** [comment]
Hi @dammy001, we reviewed your PR but we think it is too many changes in one PR, and we'd like to do this step by step. We like the refactoring you've done in the utils functions and also the [path resolution](https://github.com/tailwarden/komiser/pull/632/files#diff-9c3967d850eef2a3a17b5169df09de68ecb0f24ec46f0a9dd1b3ca7c6da7a384R19-R29) you've added! We would hapilly accept those as separate PRs, if you want. I would close this PR for now, feel free to open smaller PRs with the mentioned refactorings above. Thanks a lot!

**Comment by eneskaya** [comment]
@dammy001 Feel free to reopen with the above mentioned changes! Closing this for now

**Comment by dammy001** [comment]
Okay 👍. @eneskaya

**Pull request closed without merging**
