### PR TITLE
style(filter-component): redesign filter tag ui

### LINKED ISSUE #841: Filters bar & filters style don't match the designs
**Describe the bug**

Currently, the filters look like a button variation (because of the size) and blend into the background, looking like a cut in the layout (because of the background color).

I assume that the height of the filter was made bigger to match the button style of "Clear filters", but in this case I would suggest using the text button approach and keeping the styling of the tag different from the button.

Current implementation:

image

Figma reference:

image

**Additional context**
If you want to tackle this task, feel free to share with us your email address so we can give you access to the Figma project :)

<sub>[TECH-1281](https://linear.app/tailwarden/issue/TECH-1281/filters-bar-and-filters-style-dont-match-the-designs)</sub>

### PR DESCRIPTION
**Pull request by shobhitexe**
## Problem

The filter tags on inventory is looking more of a buttons and blending in the background

## Solution

Changes the style of tags as per figma design

## Changes Made

-  Updated the layout and styling of the filter tags.
-  Changed the positioning of the button from absolute to flex to align it within the component.

## Screenshots

https://github.com/tailwarden/komiser/assets/29349136/13c30c33-353b-45c1-b84b-f36b568766a4

## Checklist

- [x] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [x] Changes have been thoroughly tested
- [ ] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [ ] Any dependencies have been added to the project, if necessary

## Reviewers

@mlabouardy

### CODE REVIEW

**Comment by ShubhamPalriwala** [comment]
Hey @shobhitexe, thanks for the PR! 🚀  amazing work and really appreciate the screen recording! The changes look great.
However, I think, you missed the "+" symbol to add filters right next to the current filters as well?

Could you let me know what you think of that? Thanks

**Comment by shobhitexe** [comment]
> Hey @shobhitexe, thanks for the PR! 🚀 amazing work and really appreciate the screen recording! The changes look great. However, I think, you missed the "+" symbol to add filters right next to the current filters as well?
> 
> Could you let me know what you think of that? Thanks

Thank you for your feedback and appreciation, I apologize for overlooking the addition of the "+" symbol to add filters next to the current filters. I appreciate you bringing it to my attention.

Regarding your question, I can make the necessary changes and include the "+" button in the current pull request. This way, we can keep all the related changes together in one place. 
Alternatively, if you prefer, I can create a new pull request specifically for the addition of the "+" button. Please let me know your preference, and I will proceed accordingly.

Once again, thank you for your valuable feedback, and I'll make sure to address the missing "+" button promptly.

**Comment by ShubhamPalriwala** [comment]
Adding it here would be just perfect!🙌🏻 would be happy to review once pushed!

**Review by mlabouardy — CHANGES_REQUESTED** [review]
Great job @shobhitexe, LGTM!
Just missing the "+" action as mentioned by @ShubhamPalriwala :)

**Comment by shobhitexe** [comment]
Hello I have implemented the functionality for adding buttons. Please review the pull request as I have made commits in the same branch.

- included an add icon and a separator div.

- Initially, the dropdown menu and the "Filter by" button were combined into the same [component](https://github.com/tailwarden/komiser/blob/bfa89c983f5437019ccd62307442dce79df4124f/dashboard/components/inventory/components/filter/InventoryFilter.tsx#L49), which limited dropdown component reusability. To address this, I separated the dropdown into its own component, allowing it to be reused multiple times, such as in the add button. 



https://github.com/tailwarden/komiser/assets/29349136/cc9b8883-d4f3-41fe-b545-a929dc23f2da

**Comment by shobhitexe** [comment]
> Thanks for the changes @shobhitexe, I've identified a few bugs that need to be fixed :)
> 
> * The "+" button should be removed from a custom view as we don't allow users to update filters of a saved view:
> 
>  Screen.Recording.2023-06-21.at.12.21.34.mov 
> * Might be related to the first bug but if you set up a filter on a view and then you jump back to "All resources", the previous values of the filter at set in the dropdown:
> 
>  Screen.Recording.2023-06-21.at.12.24.18.mov 
> * I like that you keep the filters dropdown menu when a filter is added :) but can we close it if the filter was added from the "Filter by" button and not from the "+" button?
> 
>  Screen.Recording.2023-06-21.at.12.28.59.mov



> Thanks for the changes @shobhitexe, I've identified a few bugs that need to be fixed :)
> 
> * The "+" button should be removed from a custom view as we don't allow users to update filters of a saved view:
> 
>  Screen.Recording.2023-06-21.at.12.21.34.mov 
> * Might be related to the first bug but if you set up a filter on a view and then you jump back to "All resources", the previous values of the filter at set in the dropdown:
> 
>  Screen.Recording.2023-06-21.at.12.24.18.mov 
> * I like that you keep the filters dropdown menu when a filter is added :) but can we close it if the filter was added from the "Filter by" button and not from the "+" button?
> 
>  Screen.Recording.2023-06-21.at.12.28.59.mov

Sure , as per i understood 

- When in a saved view, there should not be any filters buttons present.
- The filters from different saved views are being saved, ( but they can be removed if we remove the filter buttons from the saved view. related to bug 1 )
- The "Filter By" button should only accept one filter at a time and then close, instead of staying open and waiting for additional filters.

Am i correct ?

**Comment by mlabouardy** [comment]
> > Thanks for the changes @shobhitexe, I've identified a few bugs that need to be fixed :)
> > 
> > * The "+" button should be removed from a custom view as we don't allow users to update filters of a saved view:
> > 
> > Screen.Recording.2023-06-21.at.12.21.34.mov
> > 
> > * Might be related to the first bug but if you set up a filter on a view and then you jump back to "All resources", the previous values of the filter at set in the dropdown:
> > 
> > Screen.Recording.2023-06-21.at.12.24.18.mov
> > 
> > * I like that you keep the filters dropdown menu when a filter is added :) but can we close it if the filter was added from the "Filter by" button and not from the "+" button?
> > 
> > Screen.Recording.2023-06-21.at.12.28.59.mov
> 
> > Thanks for the changes @shobhitexe, I've identified a few bugs that need to be fixed :)
> > 
> > * The "+" button should be removed from a custom view as we don't allow users to update filters of a saved view:
> > 
> > Screen.Recording.2023-06-21.at.12.21.34.mov
> > 
> > * Might be related to the first bug but if you set up a filter on a view and then you jump back to "All resources", the previous values of the filter at set in the dropdown:
> > 
> > Screen.Recording.2023-06-21.at.12.24.18.mov
> > 
> > * I like that you keep the filters dropdown menu when a filter is added :) but can we close it if the filter was added from the "Filter by" button and not from the "+" button?
> > 
> > Screen.Recording.2023-06-21.at.12.28.59.mov
> 
> Sure , as per i understood
> 
> * When in a saved view, there should not be any filters buttons present.
> * The filters from different saved views are being saved, ( but they can be removed if we remove the filter buttons from the saved view. related to bug 1 )
> * The "Filter By" button should only accept one filter at a time and then close, instead of staying open and waiting for additional filters.
> 
> Am i correct ?

exactly :)

**Review by ShubhamPalriwala — APPROVED** [review]
Amazing work here @shobhitexe! Love the minute details that you have handled! Lgtm. Over to you @mlabouardy 🚀

**Review by mlabouardy — APPROVED** [review]
Thanks @shobhitexe for the changes 🙏🏻

**Pull request merged**
