### PR TITLE
add dependabot

### PR DESCRIPTION
**Pull request by shivam-sharma7**
fixes: #924 

[Provide a brief description of the problem that you are trying to solve with this pull request.]

## Solution

[Provide a detailed explanation of the solution you are proposing, including any relevant code snippets or screenshots.]

## Changes Made

- [List the changes you made in this pull request, including any new features or bug fixes.]

## How to Test

[Provide instructions on how to test the changes you made, including any relevant details like configuration steps or data to be used for testing.]

## Screenshots

[Include screenshots, if relevant, to help reviewers understand the changes you made.]

## Notes

[Any additional notes or information that you would like to share with the reviewers.]

## Checklist

- [x] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [ ] Changes have been thoroughly tested
- [ ] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [ ] Any dependencies have been added to the project, if necessary

## Reviewers

@[AvineshTripathi]

### CODE REVIEW

**Comment by AvineshTripathi** [comment]
@shivam-sharma7 Thanks for raising up the PR firstly!
We also have backend written in golang so could you also look into that in the same PR. Also I am not sure what could be best way to handle both frontend and backend dependencies i.e. do we get two differnent PRs or same PR and the timing of the Pr(not sure if we could adjust that!)

If you could give more details about it that would be great!

**Comment by shivam-sharma7** [comment]
> @shivam-sharma7 Thanks for raising up the PR firstly! We also have backend written in golang so could you also look into that in the same PR. Also I am not sure what could be best way to handle both frontend and backend dependencies i.e. do we get two differnent PRs or same PR and the timing of the Pr(not sure if we could adjust that!)
> 
> If you could give more details about it that would be great!

@AvineshTripathi for now let't keep this, for backend I need to investigate :)

**Comment by AvineshTripathi** [comment]
> > @shivam-sharma7 Thanks for raising up the PR firstly! We also have backend written in golang so could you also look into that in the same PR. Also I am not sure what could be best way to handle both frontend and backend dependencies i.e. do we get two differnent PRs or same PR and the timing of the Pr(not sure if we could adjust that!)
> > If you could give more details about it that would be great!
> 
> @AvineshTripathi for now let't keep this, for backend I need to investigate :)

Sure works for me! However is there anything we should do to do the setup in our end any permissions or something? Also could you open an issue for backend with all links and resources you used for frontend which can be used by anyone who is willing to add backend support

LGTM!

**Review by ShubhamPalriwala — COMMENTED** [review]
Hey @shivam-sharma7, what do you think about setting the interval to weekly or biweekly? Daily seems too frequent to me and I have seen projects getting spammed by the dependabot at the same time!

**Comment by shivam-sharma7** [comment]
> Hey @shivam-sharma7, what do you think about setting the interval to weekly or biweekly? Daily seems too frequent to me and I have seen projects getting spammed by the dependabot at the same time!

@ShubhamPalriwala Here what I thought, we know our project is using lot of dep.. and if we set interval weekly then we can get many PR by dependabot right? because it might possible many dep.. got release within the a week. If we set daily then whatever dep... will release we will get PR and easy to merge.

**Comment by AvineshTripathi** [comment]
@shivam-sharma7 are you sure if time interval is set to weekly we will get many PRs. I think, maybe wrong but every week only one PR will be created

**Comment by shivam-sharma7** [comment]
> @shivam-sharma7 are you sure if time interval is set to weekly we will get many PRs. I think, maybe wrong but every week only one PR will be created

@AvineshTripathi I made a change. That was only my opnion

**Comment by AvineshTripathi** [comment]
Thanks! We can try weekly first and also if anything goes south we can always revert changes.

**Comment by mlabouardy** [comment]
> Thanks! We can try weekly first and also if anything goes south we can always revert changes.

can we merge this PR?

**Comment by AvineshTripathi** [comment]
@shivam-sharma7 have you tested it locally?

**Comment by shivam-sharma7** [comment]
> @shivam-sharma7 have you tested it locally?

@AvineshTripathi you can merge this.

**Comment by AvineshTripathi** [comment]
@shivam-sharma7 can you show me a demo setup on your fork how it will be functioning and what configurations are we suppose to do

**Review by AvineshTripathi — APPROVED** [review]
@shivam-sharma7 thanks for this PR, we can have same for backend and other parts too

**Comment by shivam-sharma7** [comment]
> @shivam-sharma7 Thanks for raising up the PR firstly! We also have backend written in golang so could you also look into that in the same PR. Also I am not sure what could be best way to handle both frontend and backend dependencies i.e. do we get two differnent PRs or same PR and the timing of the Pr(not sure if we could adjust that!)
> 
> If you could give more details about it that would be great!

#1314

**Pull request merged**
