### PR TITLE
fix: db nil error during initiation

### PR DESCRIPTION
**Pull request by AvineshTripathi**
db db variable in the `internal.go` file was not populated by the `utils.SetupDBConnection` function and becuase of that the `db.Dialect().Name()` func returned a error in the NewApiHandler func stopping the server to start.

### CODE REVIEW

**Comment by Azanul** [comment]
@AvineshTripathi As far as I can see `utils.SetupDBConnection` function populates db when SQLite files or Postgres urls are available. This kind of change affects a larger pattern around how db (the global var) is initialised and used. Could you see why it wasn't being populated?

**Comment by AvineshTripathi** [comment]
> @AvineshTripathi As far as I can see `utils.SetupDBConnection` function populates db when SQLite files or Postgres urls are available. This kind of change affects a larger pattern around how db (the global var) is initialised and used. Could you see why it wasn't being populated?

As you see https://github.com/tailwarden/komiser/pull/1423/files#diff-67213f39b84a013e7db04664cd3ad943b7a237d97b9c6e862d10806ac27def28L31 is by default `<nil>` since its not initialized and so when we pass it to db func it actually tries to populate the `<nil>` with new db which throws expections. 

Apart from the PR another way to do this would be https://go.dev/play/p/ki1y6kY4lq2

**Comment by Azanul** [comment]
@AvineshTripathi

> when we pass it to db func it actually tries to populate the <nil> with new db which throws expections.

I did not understand this part

**Comment by AvineshTripathi** [comment]
when we are passing 
```
var db *bun.DB
```
when we pass it to `utils. SetupDBConnection`, we are passing db=nil and trying to db to it, we are actually assign a db to nil value 

https://github.com/tailwarden/komiser/pull/1423/files#diff-96521f49e302c910e49a7ecf0204bb81314694c3f216f60fc839c61a71b04b4bR37

and this must be broken with the recent major refactor

**Comment by Azanul** [comment]
> when we are passing
> 
> ```
> var db *bun.DB
> ```
> 
> when we pass it to `utils. SetupDBConnection`, we are passing db=nil and trying to db to it, we are actually assign a db to nil value
> 
> https://github.com/tailwarden/komiser/pull/1423/files#diff-96521f49e302c910e49a7ecf0204bb81314694c3f216f60fc839c61a71b04b4bR37
> 
> and this must be broken with the recent major refactor

I see

**Review by Azanul — APPROVED** [review]
Awesome work!

**Pull request merged**
