### PR TITLE
add owner tags for jobs and pods

### PR DESCRIPTION
**Pull request by shubhindia**
## Problem

Currently, komiser doesn't support listing cronJobs

## Solution

This PR adds support for listing cronJobs and their pricing as well

## Changes Made

- Added separate function to fetch cronJobs
- Fixed incorrect log line in Jobs

## How to Test

`komiser start --config=config.toml`

## Screenshots
Screenshot 2023-10-10 at 11 54 29 AM

## Checklist

- [X] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [X] Changes have been thoroughly tested
- [ ] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [ ] Any dependencies have been added to the project, if necessary

### CODE REVIEW

**Comment by shubhindia** [comment]
QQ here, should we have tags based on ownerReference? A cronJob can create multiple jobs and then it would be easy to filter based on owner of that job. Something like this. Same can be done for others as well (most of the objects can/will have ownerReferences and it will be easier to group them by this ownerReference). Let me know if I should add it or not?
Screenshot 2023-10-10 at 12 12 38 PM

**Review by Azanul — CHANGES_REQUESTED** [review]
opencost currently classifies jobs and cronjobs under jobs, ref: https://github.com/opencost/opencost/blob/26b5ba12ac73e612b5328969debf2056478ef0d7/pkg/costmodel/costmodel.go#L128C1-L138C1

There is no separate aggregation by cronjob.

**Comment by Azanul** [comment]
@mlabouardy What kind of coverage are we looking for regarding k8s cron jobs?

**Comment by shubhindia** [comment]
> opencost currently classifies jobs and cronjobs under jobs, ref: https://github.com/opencost/opencost/blob/26b5ba12ac73e612b5328969debf2056478ef0d7/pkg/costmodel/costmodel.go#L128C1-L138C1
> 
> There is no separate aggregation by cronjob.

My bad. I didn't check the opencost price aggregation. So, I think here it makes more sense to just add owner tags than having a separate service for cronJob? Or we can continue having cronJobs without cost?

**Comment by mlabouardy** [comment]
> @mlabouardy What kind of coverage are we looking for regarding k8s cron jobs?

as they belong to jobs, I would say collecting the owner tag would be enough

**Comment by shubhindia** [comment]
@Azanul pushed the changes. I think same can be done for pods as well. Tags can help group them together

**Review by mlabouardy — APPROVED** [review]

**Review by Azanul — APPROVED** [review]

**Pull request merged**
