### PR TITLE
refactor: changed toast to have centrilized state management and sing…

### PR DESCRIPTION
**Pull request by shavidze**
…leton approach

## Problem

Toasts are difficult to use and always need to be imported manually if not already

## Solution
Implemented  `ToastProvider`, typically provides the same instance of the toast management context throughout the entire application.

## Checklist
- [x] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [x] Changes have been thoroughly tested
- [ ] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [ ] Any dependencies have been added to the project, if necessary

## Reviewers

@Traxmaxx

### CODE REVIEW

**Comment by Traxmaxx** [comment]
hei @shavidze 

thanks so much for your contribution! It looks good already but there are still Toast imports and definitions found throughout the whole application:
`{toast && <Toast {...toast} dismissToast={dismissToast} />}`
Is this intended?

**Comment by shavidze** [comment]
> hei @shavidze
> 
> thanks so much for your contribution! It looks good already but there are still Toast imports and definitions found throughout the whole application: `{toast && <Toast {...toast} dismissToast={dismissToast} />}` Is this intended?

hi @Traxmaxx ,no I've already updated it, I missed to remove it and insert into the provider

**Review by Traxmaxx — APPROVED** [review]
LGTM really well done! 👏  Thanks for taking the time! 🙏

**Comment by shavidze** [comment]
> LGTM really well done! 👏 Thanks for taking the time! 🙏

You can always ask me for help, I'm trying to participate on the server side  too 🙏

**Review by mlabouardy — APPROVED** [review]
LGTM!

**Pull request merged**
