### PR TITLE
fix(inputs): added maxlength for inputs

### LINKED ISSUE #358: Set maxlength for custom view's name input
Set a maximum character limit in input field to avoid the following:

image

### PR DESCRIPTION
**Pull request by shobhitexe**
### Closes #358 

There was no maxLength for input fields

## Solution

Added maxLength of 64 to inputs

## Changes Made

- Added maxLength prop to [input.tsx](https://github.com/tailwarden/komiser/blob/2ea2c908b20096901b949feb21b5753ec31ac36e/dashboard/components/input/Input.tsx)
- added maxlength of 64 to input fields

## Screenshots

https://github.com/tailwarden/komiser/assets/29349136/5aa867d9-e6f1-4a9e-8b18-3a6bbea5f70d

Text not going beyond 64 chars same for all inputs

## Checklist

- [x] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [x] Changes have been thoroughly tested
- [ ] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [ ] Any dependencies have been added to the project, if necessary

## Reviewers

@mlabouardy @ShubhamPalriwala

### CODE REVIEW

**Comment by ShubhamPalriwala** [comment]
Hey @shobhitexe great work 🚀 To the point and concise changes!
Just a suggestion:
- Can we throw a warning when the max character limit gets exceeded @shobhitexe? Something like a small warning message just below the input box saying the max character limit to search has exceeded! Prolly playing around `mt-2 text-xs text-error-600`.

@mlabouardy what do you think? Or should we tackle this in a separate PR?

**Comment by shobhitexe** [comment]
> Hey @shobhitexe great work 🚀 To the point and concise changes! Just a suggestion:
> 
> * Can we throw a warning when the max character limit gets exceeded @shobhitexe? Something like a small warning message just below the input box saying the max character limit to search has exceeded! Prolly playing around `mt-2 text-xs text-error-600`.
> 
> @mlabouardy what do you think? Or should we tackle this in a separate PR?


Certainly, it is possible. For instance, a notification similar to this may appear, indicating that the maximum character limit has been reached. what you think
image

**Review by mlabouardy — APPROVED** [review]
Thanks a lot @shobhitexe

**Review by ShubhamPalriwala — APPROVED** [review]
Lgtm!🚀  I'll log another issue for adding a toast notification when the character limit exceeds, feel free to take that up!

**Pull request merged**
