### PR TITLE
feat: add aws codedeploy resource

### PR DESCRIPTION
**Pull request by VanshulB**
## Problem

Need to support AWS CodeDeploy Resources

## Solution

Added AWS CodeDeploy Support

## Changes Made

- Added AWS CodeDeploy Support
- Updated the Package Dependencies for the same.
## Checklist

- [x] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [x] Changes have been thoroughly tested
- [x] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [x] Any dependencies have been added to the project, if necessary

## Reviewers

@AvineshTripathi

### CODE REVIEW

**Comment by AvineshTripathi** [comment]
waiting for https://github.com/tailwarden/komiser/pull/1216 to merge

**Review by AvineshTripathi — APPROVED** [review]

**Comment by Azanul** [comment]
@VanshulB Could you resolve the conflicts?
You'll probably have to rebase (to accommodate the version upgrade) but the code changes will remain the same.

**Comment by VanshulB** [comment]
Hey @Azanul , I have done the rebase and resolved the merge conflict by force pushing.

**Review by Azanul — APPROVED** [review]
Well done @VanshulB !!!

**Pull request merged**
