### PR TITLE
fix(dashboard): added calenderSelect component, react-calendar

### PR DESCRIPTION
**Pull request by AlexVCS**
## Problem

[Provide a brief description of the problem that you are trying to solve with this pull request.]
#854 Allow user to set a custom date period in the cost explorer widget

## Solution

[Provide a detailed explanation of the solution you are proposing, including any relevant code snippets or screenshots.]
Still in progress, but adding React-calendar https://www.npmjs.com/package/react-calendar integration.

## Changes Made

- [List the changes you made in this pull request, including any new features or bug fixes.]
- Made new calendarselect component
- added react-calendar and styles

## How to Test

[Provide instructions on how to test the changes you made, including any relevant details like configuration steps or data to be used for testing.]

## Screenshots

[Include screenshots, if relevant, to help reviewers understand the changes you made.]

## Notes

[Any additional notes or information that you would like to share with the reviewers.]

## Checklist

- [ ] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [ ] Changes have been thoroughly tested
- [ ] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [✅ ] Any dependencies have been added to the project, if necessary

## Reviewers

@[username of the reviewer]

### CODE REVIEW

**Review by mlabouardy — COMMENTED** [review]
Is this PR ready for review @AlexVCS?

**Comment by ShubhamPalriwala** [comment]
Hey @AlexVCS, hope you're doing well! Any update on this PR? Do you need some help?

**Comment by AvineshTripathi** [comment]
Hey @AlexVCS this PR has been for a while now if you have less bandwidth to complete this draft can we close this and link it to the issue for reference to folks who want to solve this issue or even better who wants to collaborate with you.

**Comment by mlabouardy** [comment]
> Hey @AlexVCS this PR has been for a while now if you have less bandwidth to complete this draft can we close this and link it to the issue for reference to folks who want to solve this issue or even better who wants to collaborate with you.

Hey @AlexVCS I'm closing the PR for now since no update for a while. Feel free to open the PR again once its ready for review :)

**Pull request closed without merging**
