### PR TITLE
[FEAT-1092]: Update color names and box-shadows to match Design-System

### PR DESCRIPTION
**Pull request by umrkhn**
Fixes: #1092

## Description
This PR updates color names and box-shadows to be consistent with komiser's design system.
## Changes Made

- update colors & box-shadows in `tailwind.config.js` 
- update class-names for colors & box-shadows

## Notes

[Any additional notes or information that you would like to share with the reviewers.]

## Checklist

- [x] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [ ] Changes have been thoroughly tested
- [ ] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [ ] Any dependencies have been added to the project, if necessary

## Reviewers

@Traxmaxx @AllieMendes

### CODE REVIEW

**Review by mlabouardy — COMMENTED** [review]
Hey @umrkhn let us know if you need some help to make this PR ready for review :)

**Comment by umrkhn** [comment]
@mlabouardy I have requested some changes from @AllieMendes on Figma, will update it as soon as she responds.

**Comment by Traxmaxx** [comment]
@umrkhn Thank you!

**Comment by AllieMendes** [comment]
> Thanks @mlabouardy, I have requested some changes from @AllieMendes on Figma, will update it as soon as she responds.

Thank you so much @umrkhn! I'm back on desk and have replied on Figma

**Comment by umrkhn** [comment]
I have updated the colors & box-shadows to match the new design system however there are few components whose colors &  box-shadows dont match since the design had an update although for the scope of this issue I have laid the foundations and updated the class-names, and we can slowly align the UI with design in future PR''s

**Comment by Azanul** [comment]
@umrkhn Could you resolve the conflicts

**Comment by umrkhn** [comment]
> @umrkhn Could you resolve the conflicts

Sure :+1:

**Comment by Traxmaxx** [comment]
Hey @umrkhn sorry I'm late to the review. There is another conflict in the feedback widget. Would you be so kind to resolve it? It can be merged then 🙏

**Review by Traxmaxx — APPROVED** [review]

**Comment by Azanul** [comment]
@umrkhn sorry to ask you to do it again, I think now we'll be GTG after resolving conflicts

**Comment by umrkhn** [comment]
Sure @Azanul @Traxmaxx , anytime :+1:

**Review by Azanul — APPROVED** [review]

**Pull request merged**
