### PR TITLE
Feature/1272 add new group by option in cost explorer

### PR DESCRIPTION
**Pull request by syedbarimanjan**
Added the feature as per #1272 

## Reviewers

@Azanul

### CODE REVIEW

**Review by Azanul — APPROVED** [review]
Screenshot 2024-01-02 at 10 18 40 AM

**Comment by Azanul** [comment]
Good work @syedbarimanjan !!

**Comment by syedbarimanjan** [comment]
@AvineshTripathi

**Review by AvineshTripathi — APPROVED** [review]
Approve with a note that discussion needs to be done about the wording we share

**Comment by syedbarimanjan** [comment]
> Approve with a note that discussion needs to be done about the wording we share

didnt get you

**Comment by AvineshTripathi** [comment]
@syedbarimanjan its not for you, its for us maintainers to track down the discussions for future

**Review by mlabouardy — APPROVED** [review]

**Pull request merged**
