### PR TITLE
fix: temporarily removing onboarding wizard for updates

### PR DESCRIPTION
**Pull request by AvineshTripathi**
This PR temporarliy sets down the onboaring wizard as the backend support of the feature is still incomplete. 

Some changes on the bakend side is done in this PR but since the main functionality will take some time to be figured out it would be better to keep the feature down till then.

Problem: When a cloud in onboarded the only thing the backend does currently is updating the db however scanning the account requires creation of clients and configs which is not possible with the current architecture.

### CODE REVIEW

**Comment by Azanul** [comment]
What is `Source` field added to all config structs?

**Comment by AvineshTripathi** [comment]
To create the `config.toml` file, for Aws sources can be env_var and so all the fields that were being sent from frontend I included that

**Comment by Azanul** [comment]
@AvineshTripathi Lets only deactivate the wizard and remove everything other than that. We'll look back again after refactoring.

**Comment by AvineshTripathi** [comment]
@Azanul this should be good to go

**Review by Azanul — APPROVED** [review]
LGTM

**Review by jakepage91 — APPROVED** [review]
GTG

**Pull request merged**
