### PR TITLE
Upgrade react 18.3.1 from 18.2.0

### PR DESCRIPTION
**Pull request by shivam-sharma7**
Upgrade react 18.3.1 from 18.2.0

### CODE REVIEW

**Comment by AvineshTripathi** [comment]
It released a few days before, I am not sure if we should shift directly cc @Azanul

**Comment by shivam-sharma7** [comment]
I think its important, in order to upgrade upcomming react `19.x.x`

**Comment by Azanul** [comment]
Dependency updates, like this one, are handled reliably by dependabot.

**Comment by shivam-sharma7** [comment]
@Azanul But this upgrade was causing an error related CI I have fixed this and I belive dependabot not able to handle that

**Comment by Azanul** [comment]
> @Azanul But this upgrade was causing an error related CI I have fixed this and I belive dependabot not able to handle that

Could you link the failed CI run where this error occurred?

**Comment by Azanul** [comment]
> @Azanul This is link-https://github.com/tailwarden/komiser/actions/runs/8860507652/job/24331359874#step:4:7
> 
> I know its small error but syncking lock file is very important!

Here's a successful CI run without the changes in this PR. 
https://github.com/tailwarden/komiser/actions/runs/9125408769/job/25091527173?pr=1419

**Comment by shivam-sharma7** [comment]
@Azanul Does that PR contains React 18.3..1? I think no, So what you want to tell me? check your PR file changes- https://github.com/tailwarden/komiser/pull/1419/files I'm not seeing anything related react.

**Comment by Azanul** [comment]
> @Azanul Does that PR contains React 18.3..1? I think no, So what you want to tell me? check your PR file changes- https://github.com/tailwarden/komiser/pull/1419/files I'm not seeing anything related react.

It's not required. That's the point.

**Pull request closed without merging**
