### PR TITLE
[KOM-38]: Resource fetching performance improvement for CIVO, DigitalOcean, OCI, Linode, K8s, Tencent

### PR DESCRIPTION
**Pull request by bishal7679**
## Problem

#1198 #1199 #1200 #1201 #1202 #1203

## Solution

Submitting the tasks to worker pool instead of executing synchronously.

## Changes Made

- Updated respective function signatures
- Used `providers.WorkerPool.SubmitTask` to submit the task to worker pool

## Checklist

- [x] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [x] Changes have been thoroughly tested
- [x] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [x] Any dependencies have been added to the project, if necessary

### CODE REVIEW

**Comment by bishal7679** [comment]
Creating a single PR to avoid repeating same!

**Comment by AvineshTripathi** [comment]
Hey @bishal7679 Civo is showing following logs which are incorrect 

and I think it would be same for Tencent support. The reason behind this is likely to be with the region variable. We faced the same issue for AWS resources and moved with cloning the client. Please see to it

**Comment by bishal7679** [comment]
@AvineshTripathi Could you pls check once now?

**Comment by bishal7679** [comment]
@Azanul PHAL here!

**Comment by AvineshTripathi** [comment]
LGTM

**Review by Azanul — APPROVED** [review]

**Review by AvineshTripathi — APPROVED** [review]

**Pull request merged**
