### PR TITLE
FIX: Onboarding wizard

### PR DESCRIPTION
**Pull request by Azanul**
## Problem

Unstable onboarding wizard

## Solution

Stable onboarding wizard

## Changes Made

- DB creation/selection first then cloud account
- Added a helper file in handlers folder to circumvent cyclic import issue

## Notes

Will refactor to clean code in near future to avoid issues like cyclic import completely without repeating code

## Checklist

- [X] Code follows the <a href="https://github.com/tailwarden/komiser/blob/master/CONTRIBUTING.md">contributing</a> guidelines
- [X] Changes have been thoroughly tested
- [X] <a href="https://github.com/tailwarden/docs.komiser.io">Documentation</a> has been updated, if necessary
- [X] Any dependencies have been added to the project, if necessary

### CODE REVIEW

**Comment by Azanul** [comment]
@jakepage91 could you check if the onboarding wizard works for you on this branch.

**Comment by jakepage91** [comment]
Just did, doesn't seem to be working unfortunately.

**Comment by AvineshTripathi** [comment]
ref #1273 for context

**Comment by jakepage91** [comment]
Hey there @AvineshTripathi I have seen the comment on your other issue, I see that you mention that ENV VARS should be used in the onboarding wizard. Having done this I still can't get the onboarding wizard to work. 

Has this worked for either you Avinesh or @Azanul ?

**Comment by AvineshTripathi** [comment]
@jakepage91  I beleive you must be getting the weird error right. The problem is with current architecture that is not allowing the wizard to work. we are refactoring it into a new one. Plan of the changes is present in the maintainers channel

**Review by jakepage91 — APPROVED** [review]
LGTM, working on my end!

**Pull request merged**
